Repository PathSnap/PathSnap-FE, pull requests merged in 2024-11, with the labels that each got.

#9 Chore/remove dev-dist
  .gitignore
  dev-dist/registerSW.js
  dev-dist/sw.js
  dev-dist/workbox-b5f7729d.js
  dev-dist/workbox-ce62b1cc.js
Labels: chore

#10 Desgin/components home map
  package-lock.json
  package.json
  src/components/MapComponent.tsx
  src/icons/Map/CustomImageMarker.tsx
  src/icons/Map/CustomMainMarker.tsx
  src/icons/Map/MapStyles.css
  src/pages/MainPage.tsx
Labels: design

#6 Design/components home navbar
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  src/App.tsx
  src/components/Footer.tsx
  src/icons/Footer/IconHome.tsx
  src/icons/Footer/IconPerson.tsx
  src/index.css
  tailwind.config.js
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: design

#14 Design/components home bottom sheet
  package.json
  src/App.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/BottomSheet/SelectBox.tsx
  src/components/Footer.tsx
  src/icons/BottomSheeet/IconCar.tsx
  src/icons/BottomSheeet/IconDrag.tsx
  src/icons/BottomSheeet/IconPlus.tsx
  src/index.css
  src/pages/MainPage.tsx
  tailwind.config.js
Labels: design

#21 Design/pages login
  src/App.tsx
  src/components/Input.tsx
  src/icons/Frame 1000002379.svg
  src/icons/IconBack.tsx
  src/icons/LoginPage/IconKakao.tsx
  src/icons/LoginPage/IconNaver.tsx
  src/pages/AddFriendPage.tsx
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
Labels: design

#23 Feat/components home bottom sheet modify and delete
  public/cute.png
  src/components/BottomSheet/BottomSheet.tsx
  src/components/BottomSheet/Records/LocationRecord.tsx
  src/components/BottomSheet/Records/PhotoRecord.tsx
  src/components/BottomSheet/Records/RecordWrapper.tsx
  src/components/BottomSheet/SelectBox.tsx
  src/components/Modals/AddPhotoModal.tsx
  src/components/Modals/PhotoDetailModal.tsx
  src/css/PhotoSlider.css
  src/css/tailwind.css
  src/hooks/BottomSheet/useBottomSheet.tsx
  src/icons/BottomSheeet/IconContent.tsx
  src/icons/BottomSheeet/IconDrag.tsx
  src/icons/BottomSheeet/IconEdit.tsx
  src/icons/BottomSheeet/IconMenu.tsx
  src/icons/BottomSheeet/IconTrash.tsx
  src/icons/IconClose.tsx
  src/index.css
  src/pages/AddFriendPage.tsx
  src/pages/ModalView.tsx
  src/pages/RegisterPage.tsx
  src/stores/EditRecordStore.tsx
  src/stores/RecordStore.tsx
  tailwind.config.js
Labels: feat

#31 Design/edit total design
  package-lock.json
  package.json
  src/components/Input.tsx
  src/components/Modals/AddPhotoModal.tsx
  src/components/Profile/AddressInput.tsx
  src/components/Profile/ProfileForm.tsx
  src/hooks/useOverflowInput.tsx
  src/icons/ProfilePage/IconCamera.tsx
  src/pages/EditProfilePage.tsx
  src/pages/RegisterPage.tsx
  tailwind.config.js
Labels: feat, design

#34 design: 단체/개인, 삭제 모달창 추가
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/BottomSheet/Records/RecordWrapper.tsx
  src/components/Footer.tsx
  src/components/Modals/DetailModal.tsx
  src/components/Modals/ModalBackground.tsx
  src/icons/Footer/IconRecord.tsx
  src/pages/ModalView.tsx
  src/stores/DetailModalType.tsx
Labels: design
